version: '3.7'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - impress-network
    volumes:
      - node_modules:/app/node_modules
      - uploads:/app/uploads
      - express_bkup:/tmp/express_bkup
    tty: true
    restart: unless-stopped
    stdin_open: false

networks:
  impress-network:
    driver: bridge

volumes:
  node_modules:
  uploads:
  express_bkup:
